name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Environment Variables
        run: |
          echo "GIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
          echo "GIT_REF=$(git symbolic-ref -q --short HEAD || git describe --tags --exact-match)" >> $GITHUB_ENV

      - name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: mvnfunc.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:

          context: fabrikam-functions
          file: ./fabrikam-functions/Dockerfile
          push: true
          tags: |
            mvnfunc.azurecr.io/myfunc-${{ env.GIT_REF }}:${{ env.GIT_SHA }}
            mvnfunc.azurecr.io/myfunc-${{ env.GIT_REF }}:latest