# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      - name: Set Environment Variables
        run: |
          echo "GIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
          echo "GIT_REF=$(git symbolic-ref -q --short HEAD || git describe --tags --exact-match)" >> $GITHUB_ENV
 

      # - uses: azure/docker-login@v1
      #   with:
      #     login-server: mvnfunc.azurecr.io
      #     username: ${{ secrets.REGISTRY_USERNAME }}
      #     password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: mvnfunc.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      # - run: |
      #     docker build -f fabrikam-functions/Dockerfile fabrikam-functions/ -t mvnfunc.azurecr.io/myfunc-${GITHUB_REF##*/}:${GITHUB_SHA::8}
      #     docker push mvnfunc.azurecr.io/myfunc-${GITHUB_REF##*/}:${GITHUB_SHA::8}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:

          context: fabrikam-functions
          file: ./fabrikam-functions/Dockerfile
          push: true
          tags: |
            myfunc-${{ env.GIT_REF }}:${{ env.GIT_SHA }}
            myfunc-${{ env.GIT_REF }}:latest